source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'dashengLoan' do
    use_frameworks!

    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SnapKit'
    pod 'IQKeyboardManagerSwift'
    pod 'BMKLocationKit'
    pod 'Bugly'
    pod 'RTRootNavigationController'    #自定义导航栏
    
end
